### ISSUE TITLE
Doesn't work with Puppet v4.+

### ISSUE THREAD

**Issue by rullera** [Nextdoor/puppet_thycotic#17]
Any chance of coding this to work with Puppet v4.+? We have a Puppet 5.3  environment which needs this functionality and i'm attempting to update this module to work with Puppet 4.x but its not my area of expertise. 

ANy chance of providing an update to this module so it works with versions of puppet?

Thanks, 

Andrew

**Comment by rullera** [comment]
So I've managed to progress this a little further. My current stumbling block is SSL support with Soap4r. 

Debug fails on **Puppet Could not create SOAP Driver from URL https://ourinternalsecretserver/webservices/SSWebService.asmx?wsdl: SSL not supported**

From what I can see this require http-access 2.0.6 and its available here http://dev.ctor.org/download/http-access-2_0_6.tar.gz but i'm unable to retrieve it.  You can see i'm using the new httpclient 2.8.3 in the gem list below.

I've seen people suggest webwrick  but havent had any luck with this either..  
`# /opt/puppetlabs/puppet/bin/gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.3.0)
bundle (0.0.1)
bundler (1.16.1)
CFPropertyList (2.3.6)
deep_merge (1.0.1)
did_you_mean (1.1.0)
diff-lcs (1.3)
facter (3.9.3, 2.5.1)
fast_gettext (1.1.0)
filecache (1.0.2)
gettext (3.2.2)
gettext-setup (0.28)
hiera (3.4.2, 1.3.4)
hocon (1.2.5)
httpclient (2.8.3)
io-console (default: 0.4.6)
json (default: 2.0.4)
json_pure (2.1.0)
locale (2.1.2)
minitest (5.10.1)
net-ssh (4.1.0)
net-telnet (0.1.1)
oauth (0.5.1)
openssl (2.1.0, default: 2.0.5)
parseconfig (1.0.8)
power_assert (0.4.1)
psych (default: 2.2.2)
puppet (5.3.3)
rake (12.3.0, 12.0.0)
rdoc (default: 5.0.0)
rspec (3.7.0)
rspec-core (3.7.1)
rspec-expectations (3.7.0)
rspec-mocks (3.7.0)
rspec-puppet (2.6.11)
rspec-support (3.7.1)
semantic_puppet (0.1.2)
soap4r-ruby1.9 (2.0.5)
stomp (1.4.4)
test-unit (3.2.3)
text (1.3.1)
webrick (1.4.2)
xmlrpc (0.2.1)`

Any help to progress this would be appreciated. Turning SSL off on our Thycoptic server is NOT an option.

**Comment by rullera** [comment]
I found the http-access2 ruby lib here: http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/ports/distfiles/ruby/http-access-2_0_6.tar.gz 

Now i just need to figure out where to put it so puppet can find it.. 

I've tried:
 /opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/
/opt/puppetlabs/server/data/puppetserver/vendored-jruby-gems/gems/
/opt/puppetlabs/server/data/puppetserver/.gem/ruby/gems/

**Comment by blackknight36** [comment]
@rullera You can install gems needed by puppetserver using the puppetserver gem command however it looks like the http-access-2.0.6 gem is quite out of date and will not work with a modern ruby install.

Even attempting a manual install fails as shown below.

>[root@puppetmaster http-access-2_0_6]# ./install.rb 
./install.rb:8:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
./install.rb:10:in `<main>': uninitialized constant CONFIG (NameError)

**Comment by rullera** [comment]
thanks @blackknight36  for your comment.  I guess the question now is how much is this functionality worth to us to implement or should we start to investigate alternative approaches  via a different secret server implementation (eg: Vault)...

**Comment by blackknight36** [comment]
@rullera SSL support is built in to the httpclient class from what I can tell in testing.  You shouldn't need anything besides the parseconfig and filecache gems to use this module.  Personally I've only been looking at Secret Server for a few days but so far I'm not a fan.  Thycotic only appears to support Windows .Net and IIS as well so if you have a Linux environment you'd be better off looking at alternatives such as Conjur.  I met one of their developers at PuppetConf and they are a great company.

**Comment by diranged** [comment]
Hey guys.. sorry for the silence here. Indeed, we actually use this module today on PuppetServer 5.3.2.  We build the server into a Docker image, so here's the relevant commands in our Dockerfile:
```
# PuppetServer 5 supports both JRuby 1.7.27 and 9k - and includes both.
# However, the AWS-SDK uses some strange auto eager loading of classes that
# causes problems in threaded environments. See
# https://github.com/jruby/jruby/issues/3920 for the long bug on this.
#
# Puppet 9k Doc: https://puppet.com/docs/puppetserver/5.1/configuration.html#enabling-jruby-9k
ENV JRUBY_JAR="/opt/puppetlabs/server/apps/puppetserver/jruby-9k.jar"
...
# Install Bundler and use it to then install all of the Gem dependencies we
# have. This is a little different than the normal docs for Puppetserver. The
# Puppetserver docs want you to run 'puppetserver gem install <...>'. However
# we want to keep our Gemfile around so that we can kep our Puppet Servers and
# Test/Dev Environments in sync. By setting GEM_HOME when we do the bundler
# install, we tell Bundler to install the Gems into the Jruby GEM_HOME path.
#
# Also, Facter comes on the image already as a C-program now.. so we strip
# that out of our Gemfile.
ADD resources/gemrc /etc/gemrc
ADD Gemfile /Gemfile
ADD Gemfile.lock /Gemfile.lock
RUN GEM_HOME=/opt/puppetlabs/server/data/puppetserver/jruby-gems \
    BUNDLE_FORCE_RUBY_PLATFORM=true bundler install --without test
...
# Unclear why, but the aws-sdk needs to be installed manually through the
# puppetserver gem command.
RUN puppetserver gem install aws-sdk -v '3.0.1'
```

Here's our Gemfile and Gemfile.lock (relevant sections again)
```
# For the puppet_thycotic module
gem 'soap4r-ruby1.9'
gem 'parseconfig'
gem 'filecache'
gem 'httpclient', '>= 2.4.0'
```

```
    soap4r-ruby1.9 (2.0.5)
    parseconfig (1.0.8)
    filecache (1.0.2)
    httpclient (2.8.3)
```

**Comment by diranged** [comment]
Also FWIW, while we still use this module, we are almost 100% migrated to using native KMS and Hiera-Eyaml in our puppet code. We only use this now for some legacy bits that we're migrating away from. It works .. works fine .. but doing everything natively in Hiera Eyaml is cleaner.

**Comment by blackknight36** [comment]
@diranged I did some more testing on our puppet master today and it looks like this module *does* work with Puppet 4 without any issues.  Using the credentials from the test script located at https://pastebin.com/AiwzX9n2 I'm able to pull secrets so @rullera should be able to make this work as well.

Our company is actually going the opposite direction, moving from hiera/eyaml to Secret Server.

**Comment by rullera** [comment]
Thanks for the update @diranged and @blackknight36 . I'm trying to get this working with a Foreman 1.16 installation but will try and pick apart your config above @diranged and apply it to our environment. The initial use case I had i've managed to work around but longer term we will need to integrate with Secret Server.. Replacing this with something like Hashicorp's Vault is not really on the radar at the moment. I'll update this thread when I get a chance to work on it (currently not a high priority). Thanks again for the updates guys! Appreciate it.

**Comment by blackknight36** [comment]
No problem.  For future reference you can use r10k to automatically install this module.  Just add these lines to your puppetfile and then run r10k or code manager to deploy the module.

```
mod 'nextdoor-thycotic',
    :git => 'https://github.com/Nextdoor/puppet_thycotic.git'
```

If you're using rspec-puppet you'll also need to update your .fixtures.yml file.
